// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvnsh3j8dBYbdZ_0B7E5S_JiSgAhDTAO4',
    appId: '1:548850087717:web:147e87328be0cd42cccccc',
    messagingSenderId: '548850087717',
    projectId: 'rendez-vous-ef146',
    authDomain: 'rendez-vous-ef146.firebaseapp.com',
    storageBucket: 'rendez-vous-ef146.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCS5cPQg8CNaGpgxJd-qtPKxj5amY6Ds2E',
    appId: '1:548850087717:android:70b44592f0c48962cccccc',
    messagingSenderId: '548850087717',
    projectId: 'rendez-vous-ef146',
    storageBucket: 'rendez-vous-ef146.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQzIAxceb0nwda8M67_n7HPHXwcsxBtrk',
    appId: '1:548850087717:ios:1949d522a6d039a4cccccc',
    messagingSenderId: '548850087717',
    projectId: 'rendez-vous-ef146',
    storageBucket: 'rendez-vous-ef146.appspot.com',
    iosBundleId: 'com.example.rendezVousHop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQzIAxceb0nwda8M67_n7HPHXwcsxBtrk',
    appId: '1:548850087717:ios:1949d522a6d039a4cccccc',
    messagingSenderId: '548850087717',
    projectId: 'rendez-vous-ef146',
    storageBucket: 'rendez-vous-ef146.appspot.com',
    iosBundleId: 'com.example.rendezVousHop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvnsh3j8dBYbdZ_0B7E5S_JiSgAhDTAO4',
    appId: '1:548850087717:web:a80bc548fb169216cccccc',
    messagingSenderId: '548850087717',
    projectId: 'rendez-vous-ef146',
    authDomain: 'rendez-vous-ef146.firebaseapp.com',
    storageBucket: 'rendez-vous-ef146.appspot.com',
  );
}
